"""Metric explanations for Lynx Fundamental Analysis.

Each entry describes what a metric means, why it matters for value investing,
and the formula used to calculate it. Used by all UI modes (CLI, interactive,
TUI, GUI) for the 'explain' feature.
"""

from __future__ import annotations

from lynx.models import MetricExplanation

METRIC_EXPLANATIONS: dict[str, MetricExplanation] = {}

def _add(key, full_name, description, why_used, formula, category):
    METRIC_EXPLANATIONS[key] = MetricExplanation(
        key=key, full_name=full_name, description=description,
        why_used=why_used, formula=formula, category=category,
    )

# ---------------------------------------------------------------------------
# Valuation
# ---------------------------------------------------------------------------

_add("pe_trailing",
     "Price-to-Earnings Ratio (Trailing 12 Months)",
     "Compares the current stock price to the company's earnings per share over the past 12 months.",
     "The most widely used valuation metric. A low P/E may indicate undervaluation, while a high P/E suggests the market expects strong future growth. Compare within the same industry.",
     "P/E = Market Price per Share / Earnings per Share (TTM)",
     "valuation")

_add("pe_forward",
     "Price-to-Earnings Ratio (Forward)",
     "Compares the current stock price to the estimated future earnings per share for the next 12 months.",
     "Shows what investors are willing to pay for expected future earnings. If forward P/E < trailing P/E, analysts expect earnings growth.",
     "Forward P/E = Market Price per Share / Estimated Future EPS",
     "valuation")

_add("pb_ratio",
     "Price-to-Book Ratio",
     "Compares the stock price to the company's book value (total assets minus total liabilities) per share.",
     "Core metric for value investing. Benjamin Graham considered P/B < 1.5 as a value signal. P/B < 1 means the stock trades below its liquidation value.",
     "P/B = Market Price per Share / Book Value per Share",
     "valuation")

_add("ps_ratio",
     "Price-to-Sales Ratio",
     "Compares the stock price to the company's revenue per share.",
     "Useful for valuing companies with no earnings (growth-stage, cyclical downturns). A P/S < 1 is generally considered cheap.",
     "P/S = Market Cap / Total Revenue (TTM)",
     "valuation")

_add("p_fcf",
     "Price-to-Free Cash Flow",
     "Compares the market capitalization to the free cash flow generated by the company.",
     "More reliable than P/E because cash flow is harder to manipulate than earnings. A low P/FCF indicates the company generates strong cash relative to its price.",
     "P/FCF = Market Cap / Free Cash Flow",
     "valuation")

_add("ev_ebitda",
     "Enterprise Value to EBITDA",
     "Compares the total enterprise value (equity + debt - cash) to earnings before interest, taxes, depreciation, and amortization.",
     "Capital-structure-neutral valuation. EV/EBITDA < 10 is generally considered cheap. Preferred over P/E for comparing companies with different debt levels.",
     "EV/EBITDA = (Market Cap + Total Debt - Cash) / EBITDA",
     "valuation")

_add("ev_revenue",
     "Enterprise Value to Revenue",
     "Compares the total enterprise value to annual revenue.",
     "Useful for pre-profit companies or highly leveraged companies where EBITDA is distorted. EV/Revenue < 1 suggests the company is very cheap relative to sales.",
     "EV/Revenue = (Market Cap + Total Debt - Cash) / Revenue",
     "valuation")

_add("peg_ratio",
     "Price/Earnings to Growth Ratio",
     "Adjusts the P/E ratio by the earnings growth rate to account for growth expectations.",
     "PEG < 1 suggests the stock may be undervalued relative to its growth rate. Invented by Peter Lynch. Best for growth-oriented analysis.",
     "PEG = P/E Ratio / Annual EPS Growth Rate (%)",
     "valuation")

_add("dividend_yield",
     "Dividend Yield",
     "The annual dividend payment as a percentage of the stock price.",
     "Measures income return on investment. High yields (>6%) may signal financial distress or unsustainable payouts. Stable yields with growth indicate shareholder-friendly management.",
     "Dividend Yield = Annual Dividends per Share / Price per Share",
     "valuation")

_add("earnings_yield",
     "Earnings Yield",
     "The inverse of the P/E ratio, expressed as a percentage. Shows the return on each dollar invested if all earnings were distributed.",
     "Joel Greenblatt uses earnings yield as a key metric in his 'Magic Formula' investing. Compare to bond yields to assess relative attractiveness of stocks vs. bonds.",
     "Earnings Yield = EPS / Market Price per Share (= 1 / P/E)",
     "valuation")

_add("price_to_tangible_book",
     "Price to Tangible Book Value",
     "Compares the stock price to the tangible book value per share (total equity minus intangible assets).",
     "More conservative than P/B because it excludes goodwill and intangibles which may have no liquidation value. Critical for asset-heavy companies and net-net investing.",
     "P/TBV = Price / (Total Equity - Intangible Assets) / Shares",
     "valuation")

_add("price_to_ncav",
     "Price to Net Current Asset Value",
     "Compares the stock price to the net current asset value (current assets minus total liabilities) per share.",
     "Benjamin Graham's 'net-net' criterion. If price < NCAV, the stock trades below its liquidation value. A classic deep-value signal, especially for micro/nano caps.",
     "P/NCAV = Price / ((Current Assets - Total Liabilities) / Shares)",
     "valuation")

# ---------------------------------------------------------------------------
# Profitability
# ---------------------------------------------------------------------------

_add("roe",
     "Return on Equity",
     "Measures how much profit the company generates for each dollar of shareholders' equity.",
     "Warren Buffett targets ROE > 15% consistently. High ROE indicates efficient use of shareholders' capital. Watch for artificially high ROE from excessive leverage.",
     "ROE = Net Income / Shareholders' Equity",
     "profitability")

_add("roa",
     "Return on Assets",
     "Measures how efficiently the company uses its total assets to generate profit.",
     "ROA > 5% is generally good. Unlike ROE, ROA is not inflated by leverage, making it useful for comparing companies with different capital structures.",
     "ROA = Net Income / Total Assets",
     "profitability")

_add("roic",
     "Return on Invested Capital",
     "Measures the return generated on all capital invested in the business (both equity and debt).",
     "The single most important profitability metric for value investors. ROIC > 10% consistently suggests a durable competitive advantage (economic moat). ROIC > WACC means the company creates value.",
     "ROIC = NOPAT / Invested Capital = (Operating Income x (1 - Tax Rate)) / (Total Assets - Excess Cash)",
     "profitability")

_add("gross_margin",
     "Gross Margin",
     "The percentage of revenue remaining after subtracting the cost of goods sold.",
     "Indicates pricing power and production efficiency. High gross margins (>60%) often signal brand strength, intellectual property, or a niche market position. Consistent margins over time suggest a moat.",
     "Gross Margin = (Revenue - Cost of Revenue) / Revenue",
     "profitability")

_add("operating_margin",
     "Operating Margin",
     "The percentage of revenue remaining after subtracting all operating expenses (COGS, SGA, R&D).",
     "Shows the profitability of core business operations before financing and taxes. Improving operating margins over time indicate operational leverage and management efficiency.",
     "Operating Margin = Operating Income / Revenue",
     "profitability")

_add("net_margin",
     "Net Profit Margin",
     "The percentage of revenue that remains as net profit after all expenses, interest, and taxes.",
     "The bottom-line profitability metric. Net margin > 20% is excellent for most industries. Declining net margins may signal competitive pressure or rising costs.",
     "Net Margin = Net Income / Revenue",
     "profitability")

_add("fcf_margin",
     "Free Cash Flow Margin",
     "The percentage of revenue converted into free cash flow.",
     "More reliable than net margin because it measures actual cash generation. High FCF margins indicate the company can fund growth, pay dividends, and reduce debt from operations alone.",
     "FCF Margin = Free Cash Flow / Revenue = (Operating Cash Flow - Capital Expenditure) / Revenue",
     "profitability")

_add("ebitda_margin",
     "EBITDA Margin",
     "The percentage of revenue remaining as EBITDA (Earnings Before Interest, Taxes, Depreciation, and Amortization).",
     "Approximates operating cash flow profitability. Useful for comparing companies across different tax jurisdictions and capital structures. EBITDA Margin > 30% is considered excellent.",
     "EBITDA Margin = EBITDA / Revenue",
     "profitability")

# ---------------------------------------------------------------------------
# Solvency
# ---------------------------------------------------------------------------

_add("debt_to_equity",
     "Debt-to-Equity Ratio",
     "Measures the proportion of debt financing relative to equity financing.",
     "Low D/E (< 0.5) indicates conservative financing. High D/E increases financial risk, especially for cyclical businesses. Compare within industry — utilities and banks naturally carry more debt.",
     "D/E = Total Debt / Total Shareholders' Equity",
     "solvency")

_add("debt_to_ebitda",
     "Debt to EBITDA Ratio",
     "Measures how many years of EBITDA it would take to pay off all debt.",
     "Debt/EBITDA < 2 is conservative, > 4 is highly leveraged. Used by credit rating agencies and leveraged buyout analysis. Lower is better for financial stability.",
     "Debt/EBITDA = Total Debt / EBITDA",
     "solvency")

_add("current_ratio",
     "Current Ratio",
     "Measures the company's ability to pay short-term obligations with short-term assets.",
     "Current Ratio > 1.5 is healthy. < 1.0 means the company may struggle to meet near-term obligations. Critical survival metric for small and micro-cap companies.",
     "Current Ratio = Current Assets / Current Liabilities",
     "solvency")

_add("quick_ratio",
     "Quick Ratio (Acid Test)",
     "Like the current ratio but excludes inventory, which may be hard to liquidate quickly.",
     "More conservative liquidity measure. Quick Ratio > 1.0 means the company can cover short-term liabilities without selling inventory.",
     "Quick Ratio = (Current Assets - Inventory) / Current Liabilities",
     "solvency")

_add("interest_coverage",
     "Interest Coverage Ratio",
     "Measures how easily the company can pay interest on its outstanding debt from operating earnings.",
     "Interest Coverage > 4 is comfortable. < 1.5 is dangerous — the company may struggle to service its debt. Critical for assessing bankruptcy risk.",
     "Interest Coverage = Operating Income / Interest Expense",
     "solvency")

_add("altman_z_score",
     "Altman Z-Score",
     "A composite formula that predicts the probability of bankruptcy within two years.",
     "Z > 2.99: Safe zone. 1.81-2.99: Grey zone (caution). < 1.81: Distress zone (high bankruptcy risk). Developed by Edward Altman in 1968.",
     "Z = 1.2(WC/TA) + 1.4(RE/TA) + 3.3(EBIT/TA) + 0.6(MV Equity/TL) + 1.0(Sales/TA)",
     "solvency")

_add("cash_burn_rate",
     "Cash Burn Rate",
     "The annual rate at which the company is consuming cash from operations (negative operating cash flow).",
     "Critical for pre-revenue and loss-making companies (common in micro/nano caps). Determines how long the company can survive without additional financing.",
     "Cash Burn Rate = Annual Operating Cash Flow (when negative)",
     "solvency")

_add("cash_runway_years",
     "Cash Runway",
     "The number of years the company can continue operating at its current cash burn rate before running out of cash.",
     "Cash Runway < 1 year signals imminent need for dilutive financing. > 3 years provides comfortable operating buffer. Critical for pre-revenue companies.",
     "Cash Runway = Total Cash / Annual Cash Burn Rate",
     "solvency")

_add("ncav_per_share",
     "Net Current Asset Value per Share",
     "The net current asset value (current assets minus total liabilities) divided by shares outstanding.",
     "Ben Graham's net-net criterion. If the stock price is below NCAV per share, the company is trading below its liquidation value — a classic deep-value signal.",
     "NCAV/Share = (Current Assets - Total Liabilities) / Shares Outstanding",
     "solvency")

# ---------------------------------------------------------------------------
# Growth
# ---------------------------------------------------------------------------

_add("revenue_growth_yoy",
     "Revenue Growth (Year-over-Year)",
     "The percentage change in annual revenue compared to the prior year.",
     "Shows the trajectory of the business. Consistent revenue growth indicates market demand and competitive strength. Declining revenue may signal market share loss.",
     "Revenue Growth = (Revenue_Current - Revenue_Prior) / |Revenue_Prior|",
     "growth")

_add("revenue_cagr_3y",
     "Revenue CAGR (3-Year)",
     "Compound Annual Growth Rate of revenue over the past 3 fiscal years.",
     "Smooths out year-to-year volatility to show the underlying growth trend. CAGR > 10% is strong for mature companies; > 20% is typical for growth companies.",
     "CAGR = (Revenue_End / Revenue_Start)^(1/3) - 1",
     "growth")

_add("revenue_cagr_5y",
     "Revenue CAGR (5-Year)",
     "Compound Annual Growth Rate of revenue over the past 5 fiscal years.",
     "Longer-term growth trend. More reliable than 3Y CAGR for assessing sustainable growth. Peter Lynch looked for consistent 15%+ revenue CAGR.",
     "CAGR = (Revenue_End / Revenue_Start)^(1/N) - 1",
     "growth")

_add("earnings_growth_yoy",
     "Earnings Growth (Year-over-Year)",
     "The percentage change in net income compared to the prior year.",
     "Earnings growth drives stock price appreciation over time. Consistent double-digit earnings growth is a strong positive signal. Watch for one-time gains distorting the number.",
     "Earnings Growth = (Net Income_Current - Net Income_Prior) / |Net Income_Prior|",
     "growth")

_add("earnings_cagr_3y",
     "Earnings CAGR (3-Year)",
     "Compound Annual Growth Rate of net income over the past 3 fiscal years.",
     "Shows whether profitability is growing or shrinking over time. More meaningful than single-year growth which can be volatile.",
     "CAGR = (Earnings_End / Earnings_Start)^(1/3) - 1",
     "growth")

_add("earnings_cagr_5y",
     "Earnings CAGR (5-Year)",
     "Compound Annual Growth Rate of net income over the past 5 fiscal years.",
     "Long-term earnings growth is the primary driver of intrinsic value. Buffett looks for predictable, steady earnings growth over 5+ years.",
     "CAGR = (Earnings_End / Earnings_Start)^(1/N) - 1",
     "growth")

_add("shares_growth_yoy",
     "Share Count Growth (Year-over-Year)",
     "The percentage change in shares outstanding compared to the prior year. Positive values indicate dilution.",
     "Share dilution destroys shareholder value. Companies that consistently buy back shares (negative growth) are returning capital to shareholders. Heavy dilution (>10%/yr) is a red flag, especially for micro caps.",
     "Share Growth = (Shares_Current - Shares_Prior) / Shares_Prior",
     "growth")

# ---------------------------------------------------------------------------
# Moat
# ---------------------------------------------------------------------------

_add("moat_score",
     "Economic Moat Score",
     "A composite score (0-100) measuring the strength of the company's competitive advantages.",
     "Inspired by Morningstar's moat methodology. Higher scores indicate more durable competitive advantages. Score > 70 suggests a wide moat; < 25 suggests no moat.",
     "Weighted average of: ROIC consistency, margin stability, revenue predictability, financial strength, and growth quality (weights vary by company tier).",
     "valuation")


# ---------------------------------------------------------------------------
# Section explanations — describe what each analysis section covers
# ---------------------------------------------------------------------------

SECTION_EXPLANATIONS: dict[str, dict[str, str]] = {
    "profile": {
        "title": "Company Profile",
        "description": (
            "Basic identifying information about the company: name, ticker, ISIN, "
            "sector, industry, country, exchange, market capitalization, employee "
            "count, and business description. The market cap determines the "
            "company's tier classification which controls which metrics are "
            "emphasized throughout the analysis."
        ),
    },
    "valuation": {
        "title": "Valuation Metrics",
        "description": (
            "Price-based ratios that compare the stock price to earnings, book "
            "value, revenue, cash flow, and other fundamentals. Low valuation "
            "ratios may signal undervaluation; high ratios suggest the market "
            "expects strong future growth. Compare within the same industry and "
            "tier for meaningful context."
        ),
    },
    "profitability": {
        "title": "Profitability Metrics",
        "description": (
            "Measures of how efficiently the company converts revenue into profit. "
            "Includes returns on equity (ROE), assets (ROA), and invested capital "
            "(ROIC), plus margin analysis at gross, operating, net, FCF, and "
            "EBITDA levels. High and stable margins are a key moat signal."
        ),
    },
    "solvency": {
        "title": "Solvency & Financial Health",
        "description": (
            "Balance sheet strength and leverage analysis. Covers debt ratios, "
            "liquidity ratios, interest coverage, and the Altman Z-Score for "
            "bankruptcy prediction. For small and micro caps, survival metrics "
            "like cash burn rate and cash runway are critical."
        ),
    },
    "growth": {
        "title": "Growth Metrics",
        "description": (
            "Revenue, earnings, and free cash flow growth rates — both "
            "year-over-year and compound annual (CAGR) over 3 and 5 years. Also "
            "tracks share dilution which is critical for small/micro caps where "
            "heavy dilution can destroy shareholder value."
        ),
    },
    "moat": {
        "title": "Economic Moat Analysis",
        "description": (
            "Qualitative and quantitative assessment of competitive advantages. "
            "For large caps: ROIC consistency, margin stability, switching costs, "
            "network effects, and cost advantages (Morningstar-style). For small "
            "and micro caps: asset backing, revenue status, niche position, and "
            "insider alignment."
        ),
    },
    "intrinsic_value": {
        "title": "Intrinsic Value Estimates",
        "description": (
            "Multiple valuation models to estimate what the company is worth. "
            "DCF (Discounted Cash Flow) is primary for large caps; Graham Number "
            "for value investors; NCAV (Net-Net) for micro/nano caps. Each method "
            "shows margin of safety — the gap between current price and estimated "
            "fair value. >25% margin = undervalued."
        ),
    },
    "financials": {
        "title": "Financial Statements",
        "description": (
            "Summary of annual income statement, balance sheet, and cash flow "
            "data for the most recent 5 fiscal years. Shows revenue, gross profit, "
            "operating income, net income, free cash flow, total equity, and total "
            "debt trends."
        ),
    },
    "filings": {
        "title": "SEC Filings",
        "description": (
            "Regulatory filings from SEC EDGAR (or equivalent exchange for "
            "international companies). Includes 10-K (annual reports), 10-Q "
            "(quarterly), 8-K (current events), and other form types. Filings "
            "can be downloaded for detailed review."
        ),
    },
    "news": {
        "title": "Recent News",
        "description": (
            "Aggregated news articles from Yahoo Finance and Google News. "
            "Provides context about recent company events, earnings reports, "
            "analyst opinions, and market sentiment."
        ),
    },
    "conclusion": {
        "title": "Assessment Conclusion",
        "description": (
            "The overall investment verdict synthesized from all analysis "
            "categories. The conclusion uses tier-weighted scoring across 5 "
            "categories (valuation, profitability, solvency, growth, moat) to "
            "produce a score from 0-100 and a verdict from 'Strong Buy' to 'Avoid'."
        ),
    },
}

CONCLUSION_METHODOLOGY = {
    "overall": {
        "title": "Conclusion Methodology",
        "description": (
            "The overall score is a weighted average of 5 category scores "
            "(valuation, profitability, solvency, growth, moat), each scored "
            "0-100. Weights vary by company tier:\n\n"
            "  Mega/Large:  Val 25%, Prof 25%, Solv 15%, Growth 15%, Moat 20%\n"
            "  Mid Cap:     Val 25%, Prof 20%, Solv 20%, Growth 20%, Moat 15%\n"
            "  Small Cap:   Val 20%, Prof 20%, Solv 25%, Growth 20%, Moat 15%\n"
            "  Micro Cap:   Val 15%, Prof 15%, Solv 35%, Growth 20%, Moat 15%\n"
            "  Nano Cap:    Val 10%, Prof 10%, Solv 40%, Growth 20%, Moat 20%\n\n"
            "Verdicts: Strong Buy (>=75), Buy (>=60), Hold (>=45), Caution (>=30), Avoid (<30).\n\n"
            "Each category score starts at a 50 baseline and is adjusted up or "
            "down based on individual metric signals. Key strengths and risks are "
            "extracted from the most significant positive and negative signals."
        ),
    },
    "valuation": {
        "title": "Valuation Score",
        "description": (
            "Starts at 50. Adjusted by: P/E trailing (+25 if <10, +15 if <15, "
            "+5 if <20, -5 if <30, -15 if >=30), P/B ratio (+20 if <1, +10 if "
            "<1.5, -10 if >=3), P/FCF (+15 if <10, +5 if <20, -10 if >=20), "
            "EV/EBITDA (+15 if <8, +5 if <12, -10 if >=12). Clamped to 0-100."
        ),
    },
    "profitability": {
        "title": "Profitability Score",
        "description": (
            "Starts at 50. Adjusted by: ROE (+15 if >20%, +5 if >10%, -15 if <0), "
            "ROIC (+15 if >15%, +5 if >10%, -15 if <0), Gross Margin (+10 if >50%, "
            "+5 if >30%, -10 if <10%), Net Margin (+10 if >15%, +5 if >5%, -15 if <0). "
            "Clamped to 0-100."
        ),
    },
    "solvency": {
        "title": "Solvency Score",
        "description": (
            "Starts at 50. Adjusted by: Debt/Equity (+15 if <0 (net cash), +10 if "
            "<0.5, -15 if >2), Current Ratio (+10 if >2, +5 if >1.5, -15 if <1), "
            "Altman Z-Score (+10 if >3, -20 if <1.8), Cash Runway (-25 if <1yr, "
            "-10 if <2yrs). Clamped to 0-100."
        ),
    },
    "growth": {
        "title": "Growth Score",
        "description": (
            "Starts at 50. Adjusted by: Revenue Growth YoY (+15 if >20%, +5 if >5%, "
            "-15 if <-10%), Earnings Growth YoY (+10 if >20%, +5 if >0, -10 if <-20%), "
            "Revenue CAGR 3Y (+10 if >10%, +5 if >0, -10 if <0), Share Dilution "
            "(+5 if buybacks >2%, -10 if dilution >10%). Clamped to 0-100."
        ),
    },
    "moat": {
        "title": "Moat Score",
        "description": (
            "The moat score (0-100) is computed in the moat calculator from: "
            "ROIC consistency and level, gross margin stability, revenue "
            "predictability, competitive position signals, and tier-specific "
            "indicators. For micro/nano caps, asset backing, niche position, "
            "and insider alignment replace traditional moat sources."
        ),
    },
}


def get_explanation(key: str) -> MetricExplanation | None:
    """Look up a metric explanation by key."""
    return METRIC_EXPLANATIONS.get(key)


def get_section_explanation(section: str) -> dict[str, str] | None:
    """Look up a section explanation by key (e.g. 'valuation', 'profile')."""
    return SECTION_EXPLANATIONS.get(section)


def get_conclusion_explanation(category: str | None = None) -> dict[str, str] | None:
    """Look up conclusion methodology.

    *category* can be 'overall', 'valuation', 'profitability', etc.
    Returns None if no explanation is found.
    """
    key = category or "overall"
    return CONCLUSION_METHODOLOGY.get(key)


def list_metrics(category: str | None = None) -> list[MetricExplanation]:
    """List all metric explanations, optionally filtered by category."""
    metrics = list(METRIC_EXPLANATIONS.values())
    if category:
        metrics = [m for m in metrics if m.category == category]
    return metrics
