"""HTML export — renders analysis report as a standalone HTML file."""

from __future__ import annotations

from pathlib import Path

from rich.console import Console

from lynx.models import AnalysisReport


def export_html(report: AnalysisReport, output_path: Path) -> Path:
    """Export report as a standalone HTML file using Rich's HTML export."""
    from lynx.display import display_full_report
    import lynx.display as disp

    console = Console(record=True, width=90, force_terminal=True)
    original_console = disp.console
    disp.console = console

    try:
        display_full_report(report)
    finally:
        disp.console = original_console

    html_body = console.export_html(inline_styles=True)

    import html as _html

    p = report.profile
    safe_name = _html.escape(p.name or "")
    safe_ticker = _html.escape(p.ticker or "")
    title = f"Lynx Fundamental Analysis — {safe_name} ({safe_ticker})"

    full_html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{title}</title>
<style>
  body {{
    background: #ffffff;
    color: #1a1a2e;
    font-family: 'Consolas', 'Monaco', 'Menlo', 'Noto Sans Mono', monospace;
    font-size: 14px;
    padding: 24px 40px;
    max-width: 1100px;
    margin: 0 auto;
  }}
  .highlight {{
    padding: 16px;
    border-radius: 8px;
    background: #f5f5fa;
    overflow-x: auto;
  }}
  /* Override Rich inline styles for print-friendly colors */
  .highlight span {{
    color: #1a1a2e !important;
  }}
  .highlight span[style*="color: #"] {{
    /* Keep colored text but ensure contrast on white */
  }}
  .highlight span[style*="bold"] {{
    font-weight: bold;
  }}
  h1 {{
    color: #2c5282;
    border-bottom: 2px solid #cbd5e0;
    padding-bottom: 8px;
  }}
  .footer {{
    margin-top: 32px;
    padding-top: 12px;
    border-top: 1px solid #cbd5e0;
    color: #718096;
    font-size: 12px;
    text-align: center;
  }}
  @media print {{
    body {{ background: #ffffff; color: #000000; }}
    .highlight {{ background: #fafafa; }}
  }}
</style>
</head>
<body>
<h1>{title}</h1>
<div class="highlight">
{html_body}
</div>
<div class="footer">
  Generated by Lynx Fundamental Analysis &mdash; {_html.escape(p.tier.value)}
  &bull; Data as of {report.fetched_at[:19] if report.fetched_at else 'N/A'}
</div>
{_author_footer_html()}
</body>
</html>
"""

    output_path.write_text(full_html, encoding="utf-8")
    return output_path


def _author_footer_html() -> str:
    """Author signature appended to every export."""
    try:
        from lynx_investor_core.author_footer import html_footer
        from lynx import SUITE_LABEL
        return html_footer(SUITE_LABEL)
    except ImportError:
        return ""
