"""HTML export — renders analysis report as a standalone HTML file."""

from __future__ import annotations

from pathlib import Path

from rich.console import Console

from lynx.models import AnalysisReport


def export_html(report: AnalysisReport, output_path: Path) -> Path:
    """Export report as a standalone HTML file using Rich's HTML export."""
    from lynx.display import display_full_report
    import lynx.display as disp

    console = Console(record=True, width=120, force_terminal=True)
    original_console = disp.console
    disp.console = console

    try:
        display_full_report(report)
    finally:
        disp.console = original_console

    html_body = console.export_html(inline_styles=True)

    p = report.profile
    title = f"Lynx FA — {p.name} ({p.ticker})"

    full_html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{title}</title>
<style>
  body {{
    background: #1e1e2e;
    color: #cdd6f4;
    font-family: 'Consolas', 'Monaco', 'Menlo', 'Noto Sans Mono', monospace;
    font-size: 14px;
    padding: 24px 40px;
    max-width: 1100px;
    margin: 0 auto;
  }}
  .highlight {{
    padding: 16px;
    border-radius: 8px;
    background: #232336;
    overflow-x: auto;
  }}
  h1 {{
    color: #89b4fa;
    border-bottom: 2px solid #45475a;
    padding-bottom: 8px;
  }}
  .footer {{
    margin-top: 32px;
    padding-top: 12px;
    border-top: 1px solid #45475a;
    color: #6c7086;
    font-size: 12px;
    text-align: center;
  }}
</style>
</head>
<body>
<h1>{title}</h1>
<div class="highlight">
{html_body}
</div>
<div class="footer">
  Generated by Lynx Fundamental Analysis &mdash; {p.tier.value}
  &bull; Data as of {report.fetched_at[:19] if report.fetched_at else 'N/A'}
</div>
</body>
</html>
"""

    output_path.write_text(full_html, encoding="utf-8")
    return output_path
