"""PDF export — converts HTML export to PDF using weasyprint (optional dependency).

Uses a dedicated HTML template optimised for A4 page layout: narrower console
width, smaller font, proper ``@page`` margins, and ``word-wrap`` to prevent
truncation.
"""

from __future__ import annotations

from pathlib import Path

from lynx.models import AnalysisReport


def _build_pdf_html(report: AnalysisReport) -> str:
    """Render the report as an HTML string optimised for A4 PDF output."""
    from rich.console import Console
    from lynx.display import display_full_report
    import lynx.display as disp

    # 90 columns: zero Rich truncation while still fitting A4 at ~8px font.
    console = Console(record=True, width=90, force_terminal=True)
    original_console = disp.console
    disp.console = console

    try:
        display_full_report(report)
    finally:
        disp.console = original_console

    raw_html = console.export_html(inline_styles=True)

    # Rich wraps output in <pre><code>…</code></pre> inside a full HTML
    # document.  We extract the inner content and supply our own wrapper
    # with PDF-optimised styling.
    import re
    # Try <code>…</code> first (most Rich versions)
    m = re.search(r'<code[^>]*>(.*)</code>', raw_html, re.DOTALL)
    if not m:
        # Fallback: <pre>…</pre>
        m = re.search(r'<pre[^>]*>(.*)</pre>', raw_html, re.DOTALL)
    if m:
        inner = m.group(1)
    else:
        # Last resort: strip outer HTML scaffolding
        inner = re.sub(r'^.*?<body[^>]*>\s*', '', raw_html, flags=re.DOTALL)
        inner = re.sub(r'\s*</body>.*$', '', inner, flags=re.DOTALL)

    import html as _html

    p = report.profile
    safe_name = _html.escape(p.name or "")
    safe_ticker = _html.escape(p.ticker or "")
    title = f"Lynx Fundamental Analysis \u2014 {safe_name} ({safe_ticker})"

    # A4 = 210 mm wide.  12 mm margins each side = 186 mm usable ≈ 703 px
    # at 96 dpi.  Weasyprint's default monospace character cell is roughly
    # 0.6 × font-size.  To fill the page: 703 px / 90 chars ≈ 7.8 px per
    # char → font-size ≈ 7.8 / 0.6 ≈ 13 px.  We use 12.6 px which gives a
    # small right margin for box-drawing characters and padding.
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>{title}</title>
<style>
  @page {{
    size: A4;
    margin: 14mm 12mm 14mm 12mm;
  }}
  body {{
    background: #ffffff;
    color: #1a1a2e;
    font-family: 'Courier New', 'Consolas', 'Monaco', 'Menlo', monospace;
    font-size: 12.6px;
    line-height: 1.25;
    padding: 0;
    margin: 0;
  }}
  code {{
    font-size: inherit;
  }}
  /* Make all Rich text dark on white — readable for print */
  pre.report span {{
    color: #1a1a2e !important;
    background-color: transparent !important;
  }}
  pre.report span[style*="bold"] {{
    font-weight: bold;
  }}
  /* Keep meaningful colours readable on white background */
  pre.report span[style*="color: #a6e3a1"],
  pre.report span[style*="color: #00ff00"],
  pre.report span[style*="color: green"] {{
    color: #16653a !important;
  }}
  pre.report span[style*="color: #f38ba8"],
  pre.report span[style*="color: red"],
  pre.report span[style*="color: #ff0000"] {{
    color: #b91c1c !important;
  }}
  pre.report span[style*="color: #f9e2af"],
  pre.report span[style*="color: yellow"] {{
    color: #92650d !important;
  }}
  pre.report span[style*="color: #89b4fa"],
  pre.report span[style*="color: cyan"],
  pre.report span[style*="color: #00ffff"] {{
    color: #1d4ed8 !important;
  }}
  h1 {{
    color: #2c5282;
    font-size: 18px;
    border-bottom: 1px solid #cbd5e0;
    padding-bottom: 4px;
    margin: 0 0 2px 0;
  }}
  pre.report {{
    font-family: inherit;
    font-size: inherit;
    line-height: inherit;
    margin: 0;
    padding: 0;
    white-space: pre-wrap;
    word-wrap: break-word;
    overflow-wrap: break-word;
  }}
  .footer {{
    margin-top: 12px;
    padding-top: 6px;
    border-top: 1px solid #cbd5e0;
    color: #718096;
    font-size: 10px;
    text-align: center;
  }}
</style>
</head>
<body>
<h1>{title}</h1>
<pre class="report">{inner}</pre>
<div class="footer">
  Generated by Lynx Fundamental Analysis &mdash; {p.tier.value}
  &bull; Data as of {report.fetched_at[:19] if report.fetched_at else 'N/A'}
</div>
</body>
</html>
"""


def export_pdf(report: AnalysisReport, output_path: Path) -> Path:
    """Export report as a PDF file.

    Requires weasyprint to be installed: pip install weasyprint
    Falls back to a helpful error message if not available.
    """
    try:
        from weasyprint import HTML
    except ImportError:
        raise RuntimeError(
            "PDF export requires weasyprint. Install it with:\n"
            "  pip install weasyprint\n"
            "Or use HTML/TXT export instead."
        )

    html_content = _build_pdf_html(report)
    HTML(string=html_content).write_pdf(str(output_path))

    return output_path
